#ifndef CCLOCK_CONFIG_H
#define CCLOCK_CONFIG_H

#define CCLOCK_FONT_NAME "Monospace:size=36"
#define CCLOCK_TEXT_BUFFER_SIZE 64
#define CCLOCK_BATTERY_TEXT_BUFFER_SIZE 64
#define CCLOCK_DATE_TEXT_BUFFER_SIZE 64
#define CCLOCK_SECONDS_TEXT_BUFFER_SIZE 64
#define CCLOCK_WORKSPACE_TEXT_BUFFER_SIZE 64
#define CCLOCK_RENDER_TEXT_BUFFER_SIZE \
    (CCLOCK_TEXT_BUFFER_SIZE + CCLOCK_DATE_TEXT_BUFFER_SIZE \
     + CCLOCK_SECONDS_TEXT_BUFFER_SIZE + CCLOCK_WORKSPACE_TEXT_BUFFER_SIZE \
     + CCLOCK_BATTERY_TEXT_BUFFER_SIZE + 2)

/* Select one of the colour profiles below, then rebuild cclock. */
#define CCLOCK_THEME_SOLID 0
#define CCLOCK_THEME_GREYSCALE 1
#define CCLOCK_COLOUR_THEME CCLOCK_THEME_GREYSCALE
/*
#define CCLOCK_COLOUR_THEME CCLOCK_THEME_SOLID
*/

/* Preserve the neutral hierarchy against light and dark root backdrops. */
#define CCLOCK_DYNAMIC_COLOURS 1

#if CCLOCK_COLOUR_THEME == CCLOCK_THEME_SOLID
/* Neutral fallback palette, kept uniform when adaptive colours are disabled. */
#define CCLOCK_TEXT_RED 0xb0b0
#define CCLOCK_TEXT_GREEN 0xb0b0
#define CCLOCK_TEXT_BLUE 0xb0b0
#define CCLOCK_TEXT_ALPHA 0xffff

#define CCLOCK_BATTERY_RED 0x9090
#define CCLOCK_BATTERY_GREEN 0x9090
#define CCLOCK_BATTERY_BLUE 0x9090
#define CCLOCK_BATTERY_ALPHA 0xffff

#define CCLOCK_DATE_RED 0x6060
#define CCLOCK_DATE_GREEN 0x6060
#define CCLOCK_DATE_BLUE 0x6060
#define CCLOCK_DATE_ALPHA 0xffff

#define CCLOCK_SECONDS_RED 0x4040
#define CCLOCK_SECONDS_GREEN 0x4040
#define CCLOCK_SECONDS_BLUE 0x4040
#define CCLOCK_SECONDS_ALPHA 0xffff

#define CCLOCK_WORKSPACE_RED 0x2020
#define CCLOCK_WORKSPACE_GREEN 0x2020
#define CCLOCK_WORKSPACE_BLUE 0x2020
#define CCLOCK_WORKSPACE_ALPHA 0xffff
#elif CCLOCK_COLOUR_THEME == CCLOCK_THEME_GREYSCALE
/* Neutral hierarchy: main and battery, date and seconds, then workspace. */
#define CCLOCK_TEXT_RED 0xb0b0
#define CCLOCK_TEXT_GREEN 0xb0b0
#define CCLOCK_TEXT_BLUE 0xb0b0
#define CCLOCK_TEXT_ALPHA 0xffff

#define CCLOCK_BATTERY_RED 0x9090
#define CCLOCK_BATTERY_GREEN 0x9090
#define CCLOCK_BATTERY_BLUE 0x9090
#define CCLOCK_BATTERY_ALPHA 0xffff

#define CCLOCK_DATE_RED 0x6060
#define CCLOCK_DATE_GREEN 0x6060
#define CCLOCK_DATE_BLUE 0x6060
#define CCLOCK_DATE_ALPHA 0xffff

#define CCLOCK_SECONDS_RED 0x4040
#define CCLOCK_SECONDS_GREEN 0x4040
#define CCLOCK_SECONDS_BLUE 0x4040
#define CCLOCK_SECONDS_ALPHA 0xffff

#define CCLOCK_WORKSPACE_RED 0x2020
#define CCLOCK_WORKSPACE_GREEN 0x2020
#define CCLOCK_WORKSPACE_BLUE 0x2020
#define CCLOCK_WORKSPACE_ALPHA 0xffff
#else
#error "unknown CCLOCK_COLOUR_THEME"
#endif

#define CCLOCK_MARGIN_RIGHT 10
#define CCLOCK_MARGIN_BOTTOM 20
#define CCLOCK_PADDING_X 8
#define CCLOCK_PADDING_Y 4

#define CCLOCK_LAYOUT_TEXT "000000000000"
/* This span uses CCLOCK_DATE_* colours; use "%m%d" for month and day. */
#define CCLOCK_DATE_FORMAT "%d"
#define CCLOCK_TIME_FORMAT "%H%M"
#define CCLOCK_SECONDS_FORMAT "%S"
#define CCLOCK_WORKSPACE_SEPARATOR ""

/* A per-user control socket is placed in $XDG_RUNTIME_DIR when available. */
#define CCLOCK_SOCKET_NAME "cclock.sock"

#endif
