#ifndef CCLOCK_CONFIG_H
#define CCLOCK_CONFIG_H

#define CCLOCK_FONT_NAME "Monospace:size=36"
#define CCLOCK_TEXT_BUFFER_SIZE 64

#define CCLOCK_TEXT_RED 0xf3f3
#define CCLOCK_TEXT_GREEN 0xf1f1
#define CCLOCK_TEXT_BLUE 0xa4a4
#define CCLOCK_TEXT_ALPHA 0xf0f0

#define CCLOCK_MARGIN_RIGHT 10
#define CCLOCK_MARGIN_BOTTOM 20
#define CCLOCK_PADDING_X 8
#define CCLOCK_PADDING_Y 4

#define CCLOCK_LAYOUT_TEXT "00:00:00"
#define CCLOCK_TIME_FORMAT "%H:%M:%S"

#endif
